################################################
### EXPERIMENT
################################################
experiment:
    DATASET: mitbih_beats
    LOADING_DIR: data
    MODULE: vaegan
    TRACKER:
        ENTITY: ecgan
        EXPERIMENT_NAME: test-vaegan
        LOCAL_SAVE: false
        LOG_LEVEL: info
        PROJECT: test
        S3_CHECKPOINT_UPLOAD: true
        SAVE_PDF: false
        TRACKER_NAME: wb
    TRAIN_ON_GPU: true

################################################
### PREPROCESSING
################################################
preprocessing:
    LOADING_DIR: data
    LOADING_SRC: shayanfazeli/heartbeat
    NUM_SAMPLES: 0
    NUM_WORKERS: 11
    RESAMPLING_ALGORITHM: lttb
    TARGET_SEQUENCE_LENGTH: 160  # original experiment used 320
    WINDOW_LENGTH: 0
    WINDOW_STEP_SIZE: 0

################################################
### TRAINER
################################################
trainer:
    BATCH_SIZE: 256
    BINARY_LABELS: true
    CHANNELS: 1
    CHECKPOINT_INTERVAL: 25
    CROSS_VAL_FOLDS: 5
    EPOCHS: 500
    MANUAL_SEED: 32199
    NUM_WORKERS: 4
    SAMPLE_INTERVAL: 5
    SPLIT: !!python/tuple
    - 0.85
    - 0.15
    SPLIT_METHOD: random
    SPLIT_PATH: split.pkl
    TRAIN_ONLY_NORMAL: true
    TRANSFORMATION: none

################################################
### MODULE
################################################
module:
    DISCRIMINATOR:
        INPUT_NORMALIZATION: none
        LAYER_SPECIFICATION:
            HIDDEN_CHANNELS:
            - 32
            - 64
            - 128
            - 256
            - 512
        LOSS:
            CLIPPING_BOUND: null
            GRADIENT_PENALTY_WEIGHT: null
            NAME: aegan_discriminator
            REDUCTION: null
        OPTIMIZER:
            ALPHA: null
            BETAS:
            - 0.9
            - 0.999
            CENTERED: null
            DAMPENING: null
            EPS: 1e-12
            LR: 0.0002
            MOMENTUM: null
            NAME: ada_belief
            WEIGHT_DECAY: 0.0
        SPECTRAL_NORM: true
        WEIGHT_INIT:
            NAME: glorot_normal
    DISCRIMINATOR_ROUNDS: 1
    ENCODER:
        INPUT_NORMALIZATION: batch
        LAYER_SPECIFICATION:
            HIDDEN_CHANNELS:
            - 32
            - 64
            - 128
            - 256
            - 512
        LOSS:
            CLIPPING_BOUND: null
            GRADIENT_PENALTY_WEIGHT: null
            NAME: vaegan_generator
            REDUCTION: null
        OPTIMIZER:
            ALPHA: null
            BETAS: !!python/tuple
            - 0.9
            - 0.999
            CENTERED: null
            DAMPENING: null
            EPS: 1.0e-16
            LR: 0.0002
            MOMENTUM: null
            NAME: ada_belief
            WEIGHT_DECAY: 0.0
        SPECTRAL_NORM: false
        WEIGHT_INIT:
            NAME: glorot_normal
    GENERATOR:
        INPUT_NORMALIZATION: batch
        LAYER_SPECIFICATION:
            HIDDEN_CHANNELS:
            - 512
            - 256
            - 128
            - 64
            - 32
        LOSS:
            CLIPPING_BOUND: null
            GRADIENT_PENALTY_WEIGHT: null
            NAME: bce_generator_loss
            REDUCTION: mean
        OPTIMIZER:
            ALPHA: null
            BETAS: !!python/tuple
                - 0.9
                - 0.999
            CENTERED: null
            DAMPENING: null
            EPS: 1.0e-16
            LR: 0.0002
            MOMENTUM: null
            NAME: ada_belief
            WEIGHT_DECAY: 0.0
        SPECTRAL_NORM: false
        TANH_OUT: false
        WEIGHT_INIT:
            NAME: glorot_normal
    GENERATOR_ROUNDS: 1
    KL_ANNEAL_ROUNDS: 0
    KL_BETA: 0.000001
    KL_WARMUP: 0
    LATENT_SIZE: 5
    LATENT_SPACE: encoder

